language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "stable"
  - "iojs"
  - "0.12"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
after_success:
  - npm run-script coveralls
